# spring.application.name=filtro_lovelace
spring:
  application:
    name: filtro_lovelace
  datasource:
    url: jdbc:mysql://localhost:3307/filtro_lovelace_db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
  servlet:
    context-path: /api/v1

# docker-compose up --build -d - construir el docker
# docker-compose down - bajar el servidor de la imagen
# docker stop - parar terminal
# docker rmi - Borrar imagn
# docker ps - Ver imagenes